name: Build Releases Binairies

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv install
      - name: Build binary
        run: pipenv run pyinstaller main.py --name zargen --onefile
      - uses: actions/upload-artifact@v2
        with:
          name: Release binary
          path: dist/
